Make sure all exit 1 go to stderr

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -174,6 +174,10 @@ else
         exit 1
     fi
     name=$GOPACKAGENAME
+else
+    err "Godep is required. For instructions:"
+    err "https://github.com/cloudfoundry/go-buildpack"
+    exit 1
 fi
 
 ver=$(expand_ver $buildpack $ver)
@@ -183,9 +187,9 @@ url=${GOURL:-$(urlfor $ver $file)}
 
 if test -e $build/bin && ! test -d $build/bin
 then
-    warn ""
+    err ""
     err "File bin exists and is not a directory."
-    warn ""
+    err ""
     exit 1
 fi
 
